--? Admin
--? guitars
--? users
--? LINIT OFFSET
--? guiatr id, details...

-- Testing table
--   id: 24
--   model_name: "Stratocaster"
--   description: "Instantly, totally familiar..."
--   price: "1600.00"
--   rating: 5
--   image_url: "image.png"
